# Generated by Django 4.2.11 on 2024-05-08 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Название изображения')),
            ],
            options={
                'verbose_name': 'Картинки слайдера',
                'verbose_name_plural': 'Картинки слайдера',
                'ordering': ['my_order'],
            },
        ),
    ]
